# Generated by Django 4.2.13 on 2026-05-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
            options={
                'db_table': 'comments_comment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='comments_co_created_5f6a12_idx'), models.Index(fields=['score'], name='comments_co_score_3380fe_idx'), models.Index(fields=['parent'], name='comments_co_parent__fdf1ec_idx'), models.Index(fields=['author'], name='comments_co_author__4d2625_idx'), models.Index(fields=['is_deleted'], name='comments_co_is_dele_370027_idx'), models.Index(fields=['parent', 'is_deleted', 'score'], name='comments_co_parent__d47dfb_idx')],
            },
        ),
    ]
